### ISSUE TITLE
nsolve

### ISSUE THREAD

**Issue by cssbue** [behrenle/NumberDrive#35]
Eingabe: nsolve(20=K0 *1,01^8)
Ausgabe: [18,47]
----
Frage: Auch bei Erweiterung des Lösungsintervalls gibt es keine Lösung:
Eingabe: nsolve(2000=K0 *1,01^8;1000;2000)
Ausgabe: []
---
Die Lösung sollte sein: 1847
-----

**Comment by behrenle** [comment]
liegt an der Grammatik des Parsers K0 wird als K * 0 interpretiert. Müsste also funktionieren, wenn man K statt K0 nimmt
