### ISSUE TITLE
asindeg(x) falscher Definitionsbereich

### ISSUE THREAD

**Issue by ukalina** [behrenle/NumberDrive#51]
asindeg(2) liefert als Ausgabe den Wert 0, obwohl die Funktion nur für \D = [-1; 1] definiert ist.

**Comment by behrenle** [comment]
ich habe den Funktionen `asin`, `acos` und `acosh` safeguards hinzugefügt, sodass diese jetzt einen Fehler ausgeben, wenn man ein invalides Argument übergibt. Da `asindeg`, `acosdeg`, mit der Sprache vom ME selbst definiert sind, gilt das für diese ebenfalls.
